### ISSUE TITLE
formatted_lyrics and align_data['align'] don't match

### ISSUE THREAD

**Issue by shoegazerstella** [SwagLyrics/autosynch#29]
I noticed this error that I am trying to fix:

```
Traceback (most recent call last):
  File "autosynch/playback.py", line 129, in <module>
    main()
  File "autosynch/playback.py", line 126, in main
    playback(**args)
  File "autosynch/playback.py", line 43, in playback
    align = line_align({'song': song, 'artist': artist, 'path': audio_file}, save)[0]['align']
  File "/Users/stella/PythonProjects/autosynch/autosynch/align.py", line 269, in line_align
    for j, line in enumerate(formatted_lyrics[i][1]):
IndexError: list index out of range
```

It seems that `formatted_lyrics` and `align_data['align']` have different lengths.

```
formatted_lyrics, len: 8

 ('verse', [['White', 'shirt', 'now', 'red,', 'my', 'bloody', 'nose'], ["Sleepin',", "you're", 'on', 'your', 'tippy', 'toes'], ["Creepin'", 'around', 'like', 'no', 'one', 'knows'], ['Think', "you're", 'so', 'criminal'], ['Bruises', 'on', 'both', 'my', 'knees', 'for', 'you'], ["Don't", 'say', 'thank', 'you', 'or', 'please'], ['I', 'do', 'what', 'I', 'want', 'when', "I'm", 'wanting', 'to'], ['My', 'soul?', 'So', 'cynical']])

 ('chorus', [['So', "you're", 'a', 'tough', 'guy'], ['Like', 'it', 'really', 'rough', 'guy'], ['Just', "can't", 'get', 'enough', 'guy'], ['Chest', 'always', 'so', 'puffed', 'guy'], ["I'm", 'that', 'bad', 'type'], ['Make', 'your', 'mama', 'sad', 'type'], ['Make', 'your', 'girlfriend', 'mad', 'tight'], ['Might', 'seduce', 'your', 'dad', 'type'], ["I'm", 'the', 'bad', 'guy'], ['Duh']])

 ('chorus', [["I'm", 'the', 'bad', 'guy']])

 ('verse', [['I', 'like', 'it', 'when', 'you', 'take', 'control'], ['Even', 'if', 'you', 'know', 'that', 'you', "don't"], ['Own', 'me,', "I'll", 'let', 'you', 'play', 'the', 'role'], ["I'll", 'be', 'your', 'animal'], ['My', 'mommy', 'likes', 'to', 'sing', 'along', 'with', 'me'], ['But', 'she', "won't", 'sing', 'this', 'song'], ['If', 'she', 'reads', 'all', 'the', 'lyrics'], ["She'll", 'pity', 'the', 'men', 'I', 'know']])

 ('chorus', [['So', "you're", 'a', 'tough', 'guy'], ['Like', 'it', 'really', 'rough', 'guy'], ['Just', "can't", 'get', 'enough', 'guy'], ['Chest', 'always', 'so', 'puffed', 'guy'], ["I'm", 'that', 'bad', 'type'], ['Make', 'your', 'mama', 'sad', 'type'], ['Make', 'your', 'girlfriend', 'mad', 'tight'], ['Might', 'seduce', 'your', 'dad', 'type'], ["I'm", 'the', 'bad', 'guy'], ['Duh']])

 ('chorus', [["I'm", 'the', 'bad', 'guy,', 'duh'], ["I'm", 'only', 'good', 'at', "bein'", 'bad,', 'bad']])

 ('bridge', [['I', 'like', 'when', 'you', 'get', 'mad'], ['I', 'guess', "I'm", 'pretty', 'glad', 'that', "you're", 'alone'], ['You', 'said', "she's", 'scared', 'of', 'me?'], ['I', 'mean,', 'I', "don't", 'see', 'what', 'she', 'sees'], ['But', 'maybe', "it's", "'cause", "I'm", 'wearing', 'your', 'cologne']])

 ('intro', [["I'm", 'a', 'bad', 'guy'], ["I'm,", "I'm", 'a', 'bad', 'guy'], ['Bad', 'guy,', 'bad', 'guy'], ["I'm", 'a', 'bad']])
```

```
align_data, len: 9

{'label': 'verse', 'syllables': 59, 'start': 1.63, 'lines': [], 'end': 14.63}
{'label': 'verse', 'syllables': 59, 'start': 55.5, 'lines': [], 'end': 74.86}
{'label': 'chorus', 'syllables': 50, 'start': 74.86, 'lines': [], 'end': 89.07}
{'label': 'chorus', 'syllables': 4, 'start': 102.59, 'lines': [], 'end': 131.05}
{'label': 'verse', 'syllables': 60, 'start': 131.05, 'lines': [], 'end': 135.33}
{'label': 'chorus', 'syllables': 50, 'start': 135.33, 'lines': [], 'end': 149.35}
{'label': 'chorus', 'syllables': 14, 'start': 149.35, 'lines': [], 'end': 163.38}
{'label': 'bridge', 'syllables': 41, 'start': 163.38, 'lines': [], 'end': 184.67}
{'label': 'intro', 'syllables': 16, 'start': 184.67, 'lines': [], 'end': 205.96}
```

`align_data` has 1 verse more (the 2nd one), and the last should be the outro but it is labeled as being the intro.
Original lyrics [here](https://genius.com/Billie-eilish-bad-guy-lyrics)

**Comment by aadibajpai** [comment]
So I can't speak for the master branch but I tried it on the branch we have deployed which uses open-unmix-pytorch instead of mad_twinnet https://github.com/SwagLyrics/autosynch/tree/umx-autosynch

It worked there so you could perhaps give that a try.

**Comment by shoegazerstella** [comment]
Oh, I did not see that branch ;)
will try and let you know then, also for the pull request.
Thanks!

**Comment by shoegazerstella** [comment]
I confirm it's working fine from your branch `umx-autosynch`, closing the issue, thanks!
